const $=s=>document.querySelector(s), canvas=$('#game-canvas'),ctx=canvas.getContext('2d');
const menu=$('#menu-screen'),game=$('#game-screen'),choice=$('#choice-overlay'),pauseBox=$('#pause-overlay'),cards=$('#cards');const player={x:24,y:210,score:0,hp:100},enemy={x:862,y:210,score:0,hp:100};const keys={up:false,down:false};let balls=[],particles=[],paused=true,reward=false,total=0,xp=0,level=1,stage=1,settings={},relics=[],audio;
const relicPool=[['Sobrecarga','Ataque speed +22% para todas as bolas.','assets/overdrive.svg','⚡',()=>relics.push('⚡ Sobrecarga')],['Colosso','Aumenta as duas raquetes em 35%.','assets/colossus.svg','◈',()=>{settings.paddle*=1.35;relics.push('◈ Colosso')}],['Gêmeas','Invoca uma segunda bola.','assets/twins.svg','✦',()=>relics.push('✦ Gêmeas')],['Égide','Recupera 25% da vida e aumenta o máximo.','assets/aegis.svg','⬟',()=>{enemy.hp=Math.min(100,enemy.hp+25);relics.push('⬟ Égide')}],['Fogo','Rebatidas aplicam queimadura: dano extra ao inimigo.','assets/piercer.svg','🔥',()=>relics.push('🔥 Fogo')],['Veneno','Cada ponto dá dano contínuo e reduz a IA.','assets/recovery.svg','☠',()=>relics.push('☠ Veneno')],['Impacto','Dano por colisão +35%.','assets/gravity.svg','✹',()=>relics.push('✹ Impacto')],['Reflexos','Velocidade das duas raquetes +35%.','assets/swift.svg','➤',()=>{settings.paddleSpeed*=1.35;relics.push('➤ Reflexos')}]];
const enemies=[['Sentinela Neon',100,1],['Gladiador Íon',130,1.12],['Aranha Violeta',160,1.2]];const bosses=[['⚡ TITÃ DE CROMO',240,1.4],['☠ RAINHA DO VENENO',300,1.55],['🔥 DRAGÃO SOLAR',380,1.7]];
function readSettings(){settings={speed:+$('#speed').value,playerColor:$('#player-color').value,cpuColor:$('#computer-color').value,theme:$('#theme').value,difficulty:$('#difficulty').value,paddle:{small:75,normal:100,large:130}[$('#paddle-size').value],paddleSpeed:8,mode:$('#ball-mode').value,effects:$('#effects').checked};localStorage.pongSettings=JSON.stringify(settings)}
function has(x){return relics.some(r=>r.includes(x))}function makeBall(dir=Math.random()>.5?1:-1){let speed=settings.speed*(has('Sobrecarga')?1.22:1);return{x:450,y:260,r:has('Impacto')?12:9,vx:dir*speed,vy:(Math.random()*4-2)||1,trail:[]}}
function resetBalls(dir=1){balls=[makeBall(dir)];if(settings.mode==='two'||has('Gêmeas'))balls.push(makeBall(-dir))}function clamp(o){o.y=Math.max(0,Math.min(520-settings.paddle,o.y))}function hit(b,o){return b.x-b.r<o.x+14&&b.x+b.r>o.x&&b.y-b.r<o.y+settings.paddle&&b.y+b.r>o.y}
function beep(f=440){if(!settings.effects)return;audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.07)}function burst(x,y,color){if(!settings.effects)return;for(let i=0;i<10;i++)particles.push({x,y,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,life:1,color})}
function updateHud(){ $('#player-score').textContent=player.score;$('#computer-score').textContent=enemy.score;$('#enemy-hp').style.width=`${Math.max(0,enemy.hp)}%`;$('#xp-bar').style.width=`${xp}%`;$('#level-label').textContent=`NV. ${level}`;$('#relics').innerHTML=relics.map(r=>`<span class="relic-chip">${r}</span>`).join('');$('#wave-label').textContent=`${stage>3?'BOSS':'ONDA'} ${Math.min(stage,3)}/3`}
function gainXp(amount){xp+=amount;if(xp>=100){xp-=100;level++;settings.speed+=.3;}}
function nextEnemy(){stage++;const isBoss=stage%4===0;const data=isBoss?bosses[(stage/4-1)%bosses.length]:enemies[(stage-1)%enemies.length];enemy.hp=data[1];enemy.score=0;$('#enemy-name').textContent=data[0];$('#stage-label').textContent=isBoss?'⚠ ARENA DE BOSS':`FASE ${stage} · RIVAL`;canvas.classList.toggle('boss-arena',isBoss);beep(isBoss?90:520);updateHud()}
function point(who){who.score++;total++;if(who===player){enemy.hp-=has('Impacto')?35:20;if(has('Fogo'))enemy.hp-=10;if(has('Veneno'))enemy.hp-=7;gainXp(18);burst(enemy.x,enemy.y,'#fbbf24');beep(720);if(enemy.hp<=0){gainXp(45);nextEnemy()}}else{player.hp=Math.max(0,player.hp-12);beep(120);if(navigator.vibrate)navigator.vibrate(80)}updateHud();if(total%2===0){showChoices();return}resetBalls(who===player?1:-1)}
function update(){if(keys.up)player.y-=settings.paddleSpeed;if(keys.down)player.y+=settings.paddleSpeed;clamp(player);const ai={easy:3.2,normal:4.7,hard:6.5}[settings.difficulty]*(has('Veneno')?.8:1);let target=balls[0]?.y-settings.paddle/2;if(target<enemy.y)enemy.y+=ai;if(target>enemy.y)enemy.y-=ai;clamp(enemy);for(let i=balls.length-1;i>=0;i--){const b=balls[i];if(settings.effects)b.trail.push({x:b.x,y:b.y});if(b.trail.length>9)b.trail.shift();b.x+=b.vx;b.y+=b.vy;if(b.y<b.r||b.y>520-b.r){b.vy*=-1;beep(260)}if(b.vx<0&&hit(b,player)){b.vx=Math.abs(b.vx)+.25;b.vy=(b.y-player.y-settings.paddle/2)/(settings.paddle/2)*settings.speed;b.x=39;burst(b.x,b.y,settings.playerColor)}if(b.vx>0&&hit(b,enemy)){b.vx=-Math.abs(b.vx)-.25;b.vy=(b.y-enemy.y-settings.paddle/2)/(settings.paddle/2)*settings.speed;b.x=847;burst(b.x,b.y,settings.cpuColor)}if(b.x<-b.r){balls.splice(i,1);point(enemy)}if(b.x>900+b.r){balls.splice(i,1);point(player)}}particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.life-=.035});particles=particles.filter(p=>p.life>0);if(!balls.length&&!paused)resetBalls(-1)}
function draw(){const c={neon:['#050816','#172554','#334155'],matrix:['#020b08','#052e16','#14532d'],sunset:['#180b19','#581c38','#9a3412'],ice:['#06121c','#164e63','#155e75']}[settings.theme];ctx.fillStyle=c[0];ctx.fillRect(0,0,900,520);ctx.strokeStyle=c[2];ctx.globalAlpha=.35;for(let y=25;y<520;y+=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(900,y);ctx.stroke()}ctx.globalAlpha=1;ctx.setLineDash([10,14]);ctx.beginPath();ctx.moveTo(450,0);ctx.lineTo(450,520);ctx.stroke();ctx.setLineDash([]);particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;function pad(o,col){ctx.shadowBlur=settings.effects?22:0;ctx.shadowColor=col;const g=ctx.createLinearGradient(o.x,0,o.x+14,0);g.addColorStop(0,'#fff');g.addColorStop(.2,col);g.addColorStop(1,'#111827');ctx.fillStyle=g;ctx.fillRect(o.x,o.y,14,settings.paddle);ctx.shadowBlur=0}pad(player,settings.playerColor);pad(enemy,settings.cpuColor);balls.forEach(b=>{if(settings.effects)b.trail.forEach((t,i)=>{ctx.globalAlpha=i/b.trail.length*.3;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(t.x,t.y,b.r*.7,0,7);ctx.fill()});ctx.globalAlpha=1;ctx.shadowBlur=settings.effects?25:0;ctx.shadowColor='#fff';ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.shadowBlur=0})}
function showChoices(){paused=true;reward=true;cards.innerHTML='';relicPool.sort(()=>Math.random()-.5).slice(0,3).forEach(r=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<img src="${r[2]}" alt="${r[0]}"><div class="card-body"><h3>${r[3]} ${r[0]}</h3><p>${r[1]}</p><button class="pick">Escolher</button></div>`;el.querySelector('button').onclick=()=>{r[4]();reward=false;choice.hidden=true;paused=false;resetBalls(1);updateHud()};cards.append(el)});choice.hidden=false}
function reset(){player.score=enemy.score=0;player.hp=100;total=xp=0;level=1;stage=1;relics=[];paused=false;reward=false;$('#enemy-name').textContent=enemies[0][0];$('#stage-label').textContent='FASE 1 · RIVAL';resetBalls();updateHud()}
function pause(v=true){if(reward)return;paused=v;pauseBox.hidden=!v}$('#settings-form').onsubmit=e=>{e.preventDefault();readSettings();reset();menu.hidden=true;game.hidden=false};$('#speed').oninput=e=>$('#speed-value').textContent=e.target.value;$('#pause-button').onclick=()=>pause(true);$('#resume-button').onclick=()=>pause(false);$('#menu-button').onclick=()=>{paused=true;game.hidden=true;menu.hidden=false};$('#pause-menu-button').onclick=()=>{pauseBox.hidden=true;game.hidden=true;menu.hidden=false};window.onkeydown=e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown')e.preventDefault();if(e.key==='ArrowUp')keys.up=true;if(e.key==='ArrowDown')keys.down=true;if(e.key==='Escape'&&!game.hidden)pause(!paused)};window.onkeyup=e=>{if(e.key==='ArrowUp')keys.up=false;if(e.key==='ArrowDown')keys.down=false};canvas.onmousemove=e=>{const r=canvas.getBoundingClientRect();player.y=(e.clientY-r.top)/r.height*520-settings.paddle/2;clamp(player)};try{const saved=JSON.parse(localStorage.pongSettings);if(saved){$('#speed').value=saved.speed;$('#player-color').value=saved.playerColor;$('#computer-color').value=saved.cpuColor;$('#theme').value=saved.theme;$('#difficulty').value=saved.difficulty;$('#effects').checked=saved.effects}}catch{};$('#speed').dispatchEvent(new Event('input'));readSettings();reset();game.hidden=true;function loop(){if(!paused){update();draw()}requestAnimationFrame(loop)}loop();
